pipeline {
  agent any

  environment {
    POM_VERSION = ''
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: '1', numToKeepStr: '2'))
  }

  triggers {
    pollSCM('* * * * *') // Проверка репозитория каждую минуту
  }

  stages {
    stage('Workspace Cleanup') {
      steps {
        cleanWs() // Очистка рабочего каталога перед всем
      }
    }

    stage('Checkout yss_cicd (infra/Jenkinsfile)') {
      steps {
        echo 'Jenkinsfile взят из yss_cicd — текущая стадия завершена автоматом.'
      }
    }

    stage('Checkout yss source (backend)') {
      steps {
        git url: 'https://github.com/Kalidratorma/yss.git', branch: 'master', credentialsId: 'github'
      }
    }

    stage('Extract version from pom.xml') {
      steps {
        script {
          POM_VERSION = sh(
            script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout',
            returnStdout: true
          ).trim()
          echo "VERSION: ${POM_VERSION}"
        }
      }
    }

    stage('Clean & Build (Maven)') {
      steps {
        sh 'mvn clean install -DskipTests=true'
      }
    }

    stage('Transfer artifact & build Docker image (Ansible)') {
      steps {
        sshPublisher(publishers: [
          sshPublisherDesc(
            configName: 'ansible-server',
            transfers: [
              sshTransfer(
                sourceFiles: "target/yss-${POM_VERSION}.jar",
                removePrefix: 'target',
                remoteDirectory: '/opt/yss',
                execCommand: "ansible-playbook /opt/yss/create_image.yml --extra-vars \"VERSION=${POM_VERSION}\"",
                execTimeout: 120000
              )
            ]
          )
        ])
      }
    }

    stage('Deploy to Kubernetes (Ansible)') {
      steps {
        sshPublisher(publishers: [
          sshPublisherDesc(
            configName: 'ansible-server',
            transfers: [
              sshTransfer(
                execCommand: "ansible-playbook -i /opt/yss/hosts /opt/yss/kube_deploy.yml --extra-vars \"VERSION=${POM_VERSION}\"",
                execTimeout: 120000
              )
            ]
          )
        ])
      }
    }
  }

  post {
    success {
      echo "✅ Backend version ${POM_VERSION} deployed successfully!"
    }
    failure {
      echo "❌ Backend build or deploy failed!"
    }
  }
}
